### DISCUSSION TITLE
Request for an easier installation

### DISCUSSION THREAD

**Discussion by equalis3r** [GideonWolfe/dots#3] [General]
Hi GideonWolfe,

I'm a very newbie to Linux so I searched the web and found your website, which is very beautiful in both appearance and writing. Your workflow and setup are beautiful too. So I tried to replicate your setup but turned out it's very difficult to get it work straight out of the box. Many links are hard coded and the dependencies are really difficult to figure out.

Is it possible that you make your setup more friendly to newbie?

Thanks a lot.

**Comment by GideonWolfe** [comment]
Thanks for reaching out @sontran94. 

You're definitely right that there is an unfortunate amount of hard coded links laying around, that's a mixture of me being lazy and also not every program knows how to parse `$HOME`, etc from their config file. 

This repo isn't really designed to be an "all in one dotfile installation", but more serves as a reference point where someone could pull the configuration for a specific program, or get inspiration for a setup of their own.

That being said, I personally manage my dotfiles using [dotdrop](https://github.com/deadc0de6/dotdrop), and I can give you my config, which will get you started as to what goes where generally.

```yaml
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
    link: link
  f_radare2rc:
    src: radare2rc
    dst: ~/.radare2rc
    link: link
  f_prompt.fish:
    src: config/fish/functions/prompt.fish
    dst: ~/.config/fish/functions/prompt.fish
    link: link
  f_functions.fish:
    src: config/fish/functions/functions.fish
    dst: ~/.config/fish/functions/functions.fish
    link: link
  f_config.fish:
    src: config/fish/config.fish
    dst: ~/.config/fish/config.fish
    link: link
  f_i3_config:
    src: config/i3/config
    dst: ~/.config/i3/config
    link: link
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
    link: link_children
  f_rofi:
    src: config/rofi/config
    dst: ~/.config/rofi/config
    link: link
  f_vdirsyncer:
    src: config/vdirsyncer/config
    dst: ~/.config/vdirsyncer/config
    link: link
  f_khal:
    src: config/khal/config
    dst: ~/.config/khal/config
    link: link
  f_khard:
    src: config/khard/khard.conf
    dst: ~/.config/khard/khard.conf
    link: link
  d_neomutt:
    src: config/neomutt
    dst: ~/.config/neomutt
    link: link_children
  d_weechat:
    src: config/weechat
    dst: ~/.config/weechat
    link: link_children
  f_newsboat_config:
    src: config/newsboat/config
    dst: ~/.config/newsboat/config
    link: link
  f_moprc:
    src: moprc
    dst: ~/.moprc
    link: link
  f_latexmkrc:
    src: latexmkrc
    dst: ~/.latexmkrc
    link: link
  f_monitor.json:
    src: config/i3/layouts/monitor.json
    dst: ~/.config/i3/layouts/monitor.json
    link: link
  d_polybar_scripts:
    src: config/polybar/scripts/
    dst: ~/.config/polybar/scripts/
    link: link_children
  f_polybar_config:
    src: config/polybar/config.ini
    dst: ~/.config/polybar/config
    link: link
  f_config.ini:
    src: config/spicetify/config.ini
    dst: ~/.config/spicetify/config.ini
    link: link
  f_color.ini:
    src: config/spicetify/Themes/wal/color.ini
    dst: ~/.config/spicetify/Themes/wal/color.ini
    link: link
  f_minimal.css:
    src: config/spicetify/Themes/wal/minimal.css
    dst: ~/.config/spicetify/Themes/wal/minimal.css
    link: link
  f_user.css:
    src: config/spicetify/Themes/wal/user.css
    dst: ~/.config/spicetify/Themes/wal/user.css
    link: link
  d_wal_templates:
    src: config/wal/templates
    dst: ~/.config/wal/templates
    link: link_children
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
    link: link
  f_glava_main_config:
    src: config/wal/templates/glava_main.glsl
    dst: ~/.config/wal/templates/glava_main.glsl
    link: link
  f_glava_bars:
    src: config/wal/templates/glava_bars.glsl
    dst: ~/.config/wal/templates/glava_bars.glsl
    link: link
  f_glava_circle:
    src: config/wal/templates/glava_circle.glsl
    dst: ~/.config/wal/templates/glava_circle.glsl
    link: link
  f_glava_graph:
    src: config/wal/templates/glava_graph.glsl
    dst: ~/.config/wal/templates/glava_graph.glsl
    link: link
  f_glava_radial:
    src: config/wal/templates/glava_radial.glsl
    dst: ~/.config/wal/templates/glava_radial.glsl
    link: link
  f_glava_wave:
    src: config/wal/templates/glava_wave.glsl
    dst: ~/.config/wal/templates/glava_wave.glsl
    link: link
  f_fzf.fish:
    src: config/wal/templates/fzf.fish
    dst: ~/.config/wal/templates/fzf.fish
    link: link
  f_neofetch_config:
    src: config/neofetch/config.conf
    dst: ~/.config/neofetch/config.conf
    link: link
  f_alacritty_colors:
    src: config/wal/templates/alacrittycolors.yml
    dst: ~/.config/wal/templates/alacrittycolors.yml
    link: link
  f_wal_rgb:
    src: config/wal/templates/wal_rgb_colors
    dst: ~/.config/wal/templates/wal_rgb_colors
    link: link
  f_wal_bashtop:
    src: config/wal/templates/bashtop_pywal.theme
    dst: ~/.config/wal/templates/bashtop_pywal.theme
    link: link
  f_starttree_config:
    src: config/StartTree/config.yaml
    dst: ~/.config/StartTree/config.yaml
    link: link
  f_dijo:
    src: config/dijo/config.toml
    dst: ~/.config/dijo/config.toml
    link: link
  f_xdg_dirs:
    src: config/xdg/user-dirs.dirs
    dst: ~/.config/user-dirs.dirs
    link: link
  f_zathurarc:
    src: config/wal/templates/zathurarc
    dst: ~/.config/wal/templates/zathurarc
    link: link
  f_picomconf:
    src: config/picom/picom.conf
    dst: ~/.config/picom/picom.conf
    link: link
  f_matplotlibrc:
    src: config/wal/templates/matplotlibrc
    dst: ~/.config/wal/templates/matplotlibrc
    link: link
  d_transmission_scripts:
    src: scripts/transmission
    dst: ~/.local/bin/transmission
    link: link_children
profiles:
  reaper:
    dotfiles:
    - f_xresources
    - f_radare2rc
    - f_prompt.fish
    - f_config.fish
    - f_functions.fish
    - f_i3_config
    - d_ranger
    - f_rofi
    - f_vdirsyncer
    - f_khal
    - f_khard
    - d_neomutt
    - d_weechat
    - f_newsboat_config
    - f_moprc
    - f_latexmkrc
    - f_monitor.json
    - d_polybar_scripts
    - f_polybar_config
    - f_config.ini
    - f_color.ini
    - f_minimal.css
    - f_user.css
    - d_wal_templates
    - f_alacritty.yml
    - f_glava_main_config
    - f_glava_bars
    - f_glava_circle
    - f_glava_graph
    - f_glava_radial
    - f_glava_wave
    - f_neofetch_config
    - f_alacritty_colors
    - f_starttree_config
    - f_wal_bashtop
    - f_wal_rgb
    - f_dijo
    - f_xdg_dirs
    - f_zathurarc
    - f_picomconf
    - f_matplotlibrc
 ```

This should give you a general idea of what from my `dotfiles` folder belongs where on my system. If you take a look at the `dotdrop` config, and adjust it to your files and needs, you will be able to install all your dotfiles (and mine) with `dotdrop install`.

In terms of dependencies, too many to count. For the programs bulleted in the `README`, I tried to include any obvious dependencies required for basic functionality. But that definitely doesn't cover random python libraries or packages automatically pulled by the Arch Linux repos as I install others. 

Feel free to ping me with any errors and I will try to see if I can figure it out.
